# Generated by Django 5.0.3 on 2024-06-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateField()),
                ('categoria', models.CharField(choices=[('Trabajo', 'Trabajo'), ('Personal', 'Personal'), ('Otro', 'Otro')], max_length=100)),
            ],
        ),
    ]
